import { useEffect, useState } from 'react'
import { repoScanReport, repoPr } from '../data/diagnostics'
import CheckCard from './CheckCard'
import BusinessForm from './BusinessForm'
import { buildPrPlan } from './repoPlan'

// The GitHub-repo report: the same six checks as the URL scan, read from the codebase instead of
// the deployed site. Pattern evidence is weaker than probe evidence, so every card names its
// provenance: measured (a real file in the repo), inferred (a framework pattern), or not
// derivable (runtime behavior source code cannot show).
//
// Below the checks, three clearly separated steps:
//   1. What the pull request will contain (and what it won't, with the reason)
//   2. Your business details (unlock llms.txt and structured data)
//   3. Create the pull request
// then the edit-target map: where in this repo each generated file belongs.
const PROVENANCE_LABEL = {
  measured: 'Measured from repo files',
  inferred: 'Inferred from framework patterns',
  'not-derivable': 'Needs a live URL scan',
}

const STATE_LABEL = { included: 'In this PR', locked: 'Needs your details', excluded: 'Not in this PR' }

const errText = (e) => (e instanceof Error ? e.message : String(e))
const PR_STATUS_TEXT = {
  opened: 'Pull request opened',
  updated: 'Existing pull request updated',
  unchanged: 'A pull request with these changes is already open',
}

function PrPlan({ rows }) {
  const included = rows.filter((r) => r.state === 'included').length
  return (
    <>
      <p className="rr-lede">
        {included === 0
          ? 'Nothing would be added to this repo yet. Add your details below to include more.'
          : `${included} file${included === 1 ? '' : 's'} would be added. Your default branch is never touched.`}
      </p>
      <ul className="pp">
        {rows.map((r) => (
          <li className={`pp-row pp-${r.state}`} key={r.id}>
            <span className="pp-state"><i aria-hidden="true" />{STATE_LABEL[r.state]}</span>
            <span className="pp-name">{r.name}</span>
            <span className="pp-impact">{r.impact}</span>
          </li>
        ))}
      </ul>
    </>
  )
}

function PrResult({ pr, onRetry }) {
  if (pr.status === 'done' && pr.result) {
    const { result } = pr
    return (
      <div className={`rr-result ${result.pr ? 'ok' : ''}`} aria-live="polite">
        <p className="rr-result-title">
          {result.pr
            ? PR_STATUS_TEXT[result.status] ?? 'Pull request opened'
            : result.status === 'no-changes'
              ? 'Nothing to change'
              : String(result.status)}
        </p>
        {!result.pr && result.status === 'no-changes' && <p>This repo already matches the generated config.</p>}
        {result.pr && (
          <p><a className="sg-btn" href={result.pr.url} target="_blank" rel="noreferrer">View pull request</a> <span className="rr-url">{result.pr.url}</span></p>
        )}
        {result.written?.length > 0 && (
          <div className="rr-list">
            <h3>Added</h3>
            <ul>{result.written.map((w) => <li key={w.path}><span className="mono">{w.path}</span> {w.what}</li>)}</ul>
          </div>
        )}
        {result.skipped?.length > 0 && (
          <div className="rr-list">
            <h3>Left out</h3>
            <ul>{result.skipped.map((s) => <li key={s.what}><b>{s.what}</b> {s.reason}</li>)}</ul>
          </div>
        )}
      </div>
    )
  }

  if (pr.status === 'install' && pr.result) {
    return (
      <div className="rr-result warn" aria-live="polite">
        <p className="rr-result-title">Install the Aperture App first</p>
        <p>{pr.result.message}</p>
        <p className="rr-actions">
          {pr.result.installUrl && <a className="sg-btn" href={pr.result.installUrl} target="_blank" rel="noreferrer">Install on GitHub</a>}
          <button className="sg-btn sg-btn-ghost" onClick={onRetry}>I installed it, try again</button>
        </p>
      </div>
    )
  }

  if (pr.status === 'error') {
    return (
      <div className="rr-result bad" aria-live="polite" role="alert">
        <p className="rr-result-title">The pull request wasn’t created</p>
        <p>{pr.error}</p>
        <p className="rr-actions"><button className="sg-btn" onClick={onRetry}>Try again</button></p>
      </div>
    )
  }
  return null
}

function TargetTable({ targets }) {
  const rows = [
    ['robots.txt', targets.robots.path, targets.robots],
    ['llms.txt', targets.llmsTxt.path, targets.llmsTxt],
    ['sitemap', targets.sitemap.path, targets.sitemap],
    ['JSON-LD', targets.headTemplate ?? '—', targets.headTemplate ? { exists: true, head: true } : { exists: false, none: true }],
  ]
  const label = (t) => {
    if (t.head) return ['ok', 'Head template found']
    if (t.none) return ['warn', 'No head template found']
    if (t.exists) return t.generated ? ['ok', 'Generated by code'] : ['ok', 'Already exists']
    return ['', 'Will be created here']
  }
  return (
    <div className="rr-table">
      <table className="dtable">
        <thead><tr><th>File</th><th>Location in the repo</th><th>Status</th></tr></thead>
        <tbody>
          {rows.map(([name, path, t]) => {
            const [tone, text] = label(t)
            return (
              <tr key={name}>
                <td>{name}</td>
                <td className="mono">{path}</td>
                <td><span className={`stat ${tone}`}>{text}</span></td>
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}

export default function RepoReport({ url, mode = 'mirror', onBack }) {
  const [scan, setScan] = useState({ status: 'loading', report: null, error: '' })
  const [attempt, setAttempt] = useState(0)
  const [open, setOpen] = useState(null)
  // idle -> working -> done | install | error. The PR lands in the repo the user submitted.
  const [pr, setPr] = useState({ status: 'idle', result: null, error: '' })
  // Business facts unlock llms.txt + JSON-LD in the PR; without them only robots.txt ships.
  const [profile, setProfile] = useState(null)

  const openPr = () => {
    setPr({ status: 'working', result: null, error: '' })
    repoPr(url, mode, profile ?? undefined)
      .then((result) => setPr({ status: result.needsInstall ? 'install' : 'done', result, error: '' }))
      .catch((e) => setPr({ status: 'error', result: null, error: errText(e) }))
  }

  useEffect(() => {
    let live = true
    setScan({ status: 'loading', report: null, error: '' })
    repoScanReport(url)
      .then((report) => { if (live) setScan({ status: 'ready', report, error: '' }) })
      .catch((e) => { if (live) setScan({ status: 'error', report: null, error: errText(e) }) })
    return () => { live = false }
  }, [url, attempt])

  const { report } = scan
  const scoreable = report ? report.checks.filter((c) => c.status !== 'na') : []
  const passed = scoreable.filter((c) => c.status === 'ok').length
  const rows = report ? buildPrPlan(report, mode, profile) : []
  const working = pr.status === 'working'
  const showButton = pr.status === 'idle' || working

  return (
    <div className="rp rr">
      <div className="rt" role="tablist" aria-label="Repo report">
        <button role="tab" aria-selected="true" className="rt-tab">Repo insights</button>
        <button className="rt-back" onClick={onBack}>◄ Change exposure</button>
      </div>

      {scan.status === 'loading' && (
        <div className="sg-status" role="status">
          <div className="rs-spin" aria-hidden="true" />
          <div>
            <div className="rs-loading-title">Cloning and scanning the repository…</div>
            <div className="rs-loading-sub">{url}</div>
          </div>
        </div>
      )}

      {scan.status === 'error' && (
        <div className="sg-status sg-error" role="alert">
          <div>
            <div className="rs-loading-title">We couldn’t scan this repository</div>
            <div className="rs-loading-sub">{scan.error}</div>
          </div>
          <button className="sg-btn" onClick={() => setAttempt((n) => n + 1)}>Try again</button>
        </div>
      )}

      {scan.status === 'ready' && report && (
        <div role="tabpanel">
          <section aria-labelledby="repo-head">
            <div className="ins-h" id="repo-head">
              <span>
                {passed} of {scoreable.length} scoreable checks pass · {report.framework.framework} ({report.framework.rendering})
                {report.appRoot ? ` · app root: ${report.appRoot}/` : ''}
              </span>
            </div>
          </section>

          <section aria-labelledby="repo-checks">
            <div className="ins-h" id="repo-checks"><span>The six checks, read from the codebase</span></div>
            <div className="cc-grid">
              {report.checks.map((c) => (
                <CheckCard
                  key={c.id} label={c.label} status={c.status} headline={c.headline} sub={c.sub} share={0}
                  open={open === c.id} onToggle={() => setOpen(open === c.id ? null : c.id)}
                >
                  <p className="rr-prov">{PROVENANCE_LABEL[c.provenance] ?? c.provenance}</p>
                  {Object.keys(c.evidence).length > 0 && <pre className="rr-evidence">{JSON.stringify(c.evidence, null, 2)}</pre>}
                </CheckCard>
              ))}
            </div>
          </section>

          <section className="rr-step" aria-labelledby="repo-pr">
            <div className="rr-h"><span className="rr-num">1</span><h2 id="repo-pr">What the pull request will contain</h2></div>
            <PrPlan rows={rows} />
          </section>

          {/* Cloak hides content from AI, so no fact files are ever written: asking for details would be pointless. */}
          {mode !== 'cloak' && (
            <section className="rr-step" aria-labelledby="repo-details">
              <div className="rr-h"><span className="rr-num">2</span><h2 id="repo-details">Your business details</h2></div>
              <p className="rr-lede">Optional. These unlock llms.txt and structured data. We only write what you enter here.</p>
              <BusinessForm
                variant="manual" prefill={profile ?? {}} evidence={{}} missing={[]}
                busy={working} defaultOpen={false}
                onApply={(p) => setProfile(p)}
              />
            </section>
          )}

          <section className="rr-step" aria-labelledby="repo-create">
            <div className="rr-h"><span className="rr-num">{mode === 'cloak' ? 2 : 3}</span><h2 id="repo-create">Create the pull request</h2></div>
            {showButton && (
              <div className="rr-action">
                <button className="sg-btn sg-btn-lg" onClick={openPr} disabled={working} aria-busy={working}>
                  {working ? 'Opening the pull request…' : `Create pull request (${mode} mode)`}
                </button>
                <p className="rr-note" aria-live="polite">
                  {working
                    ? 'Cloning your repo and writing the files. This usually takes 5 to 15 seconds, and nothing is pushed until the changes are ready.'
                    : <>Commits the files to a new <code>geo/</code> branch in <b>this repo</b> and opens a pull request for you to review.</>}
                </p>
              </div>
            )}
            <PrResult pr={pr} onRetry={openPr} />
          </section>

          <section className="rr-step" aria-labelledby="repo-targets">
            <div className="rr-h"><h2 id="repo-targets">Where each file goes in this repo</h2></div>
            <TargetTable targets={report.editTargets} />
          </section>
        </div>
      )}
    </div>
  )
}
