import { useEffect, useState } from 'react'
import { repoScanReport, repoPr } from '../data/diagnostics'
import CheckCard from './CheckCard'
import BusinessForm from './BusinessForm'

// The GitHub-repo report: the same six checks as the URL scan, read from the codebase instead of
// the deployed site. Pattern evidence is weaker than probe evidence, so every card names its
// provenance — measured (a real file in the repo), inferred (a framework pattern), or not
// derivable (runtime behavior source code cannot show). Below the checks: the edit-target map,
// i.e. where in this repo the generated files belong (the PR harness consumes the same map).
const PROVENANCE_LABEL = {
  measured: 'measured from repo files',
  inferred: 'inferred from patterns',
  'not-derivable': 'needs a live URL scan',
}

function TargetRow({ label, target }) {
  return (
    <tr>
      <td className="mono">{label}</td>
      <td className="mono">{target.path}</td>
      <td>{target.exists ? (target.generated ? 'generated by code' : 'exists') : 'missing — recommended location'}</td>
    </tr>
  )
}

// What the PR will contain, shown BEFORE the button — with the part that manages expectations:
// whether each file actually moves a failing check, or is protective-only for this repo.
function PrPreview({ report, hasProfile }) {
  const status = (id) => report.checks.find((c) => c.id === id)?.status
  const headHtml = report.editTargets.headTemplate?.endsWith('.html')
  const rows = [
    {
      name: 'robots.txt', state: 'ready',
      impact: status('access') === 'ok' ? 'no score change — crawler access already passes; this locks it in explicitly' : 'fixes the failing crawler-access check',
    },
    {
      name: 'llms.txt', state: hasProfile ? 'ready' : 'locked',
      impact: hasProfile ? 'built from your details' : 'unlocks when you fill in your details below',
    },
    {
      name: 'JSON-LD (structured data)',
      state: hasProfile ? 'ready' : 'locked',
      impact:
        (status('structured') === 'bad' ? 'fixes the failing structured-data check' : 'refreshes structured data') +
        (headHtml
          ? ''
          : ` — via a guarded Claude edit of ${report.editTargets.headTemplate ?? 'the layout'} (insertion-only, exact facts)`) +
        (hasProfile ? '' : ' — unlocks when you fill in your details below'),
    },
  ]
  const extraction = status('extraction')
  return (
    <div className="mono" style={{ marginBottom: '0.75rem' }}>
      {rows.map((r) => (
        <p key={r.name} style={{ margin: '0.15rem 0' }}>
          {r.state === 'ready' ? '＋' : r.state === 'locked' ? '🔒' : '—'} <b>{r.name}</b> — {r.impact}
        </p>
      ))}
      {extraction === 'bad' && (
        <p style={{ margin: '0.4rem 0 0', opacity: 0.75 }}>
          Not in this PR: fixing the failing extraction check means prerendering the app (a build change, not a config file).
        </p>
      )}
    </div>
  )
}

export default function RepoReport({ url, mode = 'mirror', onBack }) {
  const [scan, setScan] = useState({ status: 'loading', report: null, error: '' })
  const [open, setOpen] = useState(null)
  // idle -> working -> done | install | error. The PR lands in the repo the user submitted.
  const [pr, setPr] = useState({ status: 'idle', result: null, error: '' })
  // Business facts unlock llms.txt + JSON-LD in the PR; without them only robots.txt ships.
  const [profile, setProfile] = useState(null)

  const openPr = () => {
    setPr({ status: 'working', result: null, error: '' })
    repoPr(url, mode, profile ?? undefined)
      .then((result) => setPr({ status: result.needsInstall ? 'install' : 'done', result, error: '' }))
      .catch((e) => setPr({ status: 'error', result: null, error: e instanceof Error ? e.message : String(e) }))
  }

  useEffect(() => {
    let live = true
    setScan({ status: 'loading', report: null, error: '' })
    repoScanReport(url)
      .then((report) => { if (live) setScan({ status: 'ready', report, error: '' }) })
      .catch((e) => { if (live) setScan({ status: 'error', report: null, error: e instanceof Error ? e.message : String(e) }) })
    return () => { live = false }
  }, [url])

  const { report } = scan
  const scoreable = report ? report.checks.filter((c) => c.status !== 'na') : []
  const passed = scoreable.filter((c) => c.status === 'ok').length

  return (
    <div className="rp">
      <div className="rt" role="tablist" aria-label="Repo report">
        <button role="tab" aria-selected="true" className="rt-tab">Repo insights</button>
        <button className="rt-back" onClick={onBack}>◄ Change exposure</button>
      </div>

      {scan.status === 'loading' && <p className="mono" style={{ padding: '2rem' }}>Cloning and scanning {url}…</p>}
      {scan.status === 'error' && <p className="mono" style={{ padding: '2rem' }}>{scan.error}</p>}

      {scan.status === 'ready' && report && (
        <div role="tabpanel">
          <section aria-labelledby="repo-head">
            <div className="ins-h" id="repo-head">
              <span>
                {passed} of {scoreable.length} scoreable checks pass · {report.framework.framework} ({report.framework.rendering})
                {report.appRoot ? ` · app root: ${report.appRoot}/` : ''}
              </span>
            </div>
          </section>

          <section aria-labelledby="repo-checks">
            <div className="ins-h" id="repo-checks"><span>The six checks — from the codebase</span></div>
            {report.checks.map((c) => (
              <CheckCard
                key={c.id} label={c.label} status={c.status} headline={c.headline} sub={c.sub} share={0}
                open={open === c.id} onToggle={() => setOpen(open === c.id ? null : c.id)}
              >
                <p className="mono">Provenance: {PROVENANCE_LABEL[c.provenance] ?? c.provenance}</p>
                {Object.keys(c.evidence).length > 0 && (
                  <pre className="mono" style={{ whiteSpace: 'pre-wrap', overflowX: 'auto' }}>
                    {JSON.stringify(c.evidence, null, 2)}
                  </pre>
                )}
              </CheckCard>
            ))}
          </section>

          <section aria-labelledby="repo-pr">
            <div className="ins-h" id="repo-pr"><span>Apply the fixes</span></div>
            <PrPreview report={report} hasProfile={!!profile} />
            <BusinessForm
              prefill={profile ?? {}} evidence={{}} missing={profile ? [] : ['name', 'phone', 'address']}
              busy={pr.status === 'working'} defaultOpen={false}
              onApply={(p) => setProfile(p)}
            />
            {profile && <p className="mono">Details saved — the PR will also include llms.txt and a JSON-LD block built from them.</p>}
            {(pr.status === 'idle' || pr.status === 'working') && (
              <div>
                <button className="sg-btn sg-btn-lg" onClick={openPr} disabled={pr.status === 'working'} aria-busy={pr.status === 'working'}>
                  {pr.status === 'working' ? 'Working — cloning your repo, writing config, opening the PR…' : `Create pull request (${mode} mode)`}
                </button>
                {pr.status === 'idle' && (
                  <p className="mono">Commits the generated files to a new <code>geo/</code> branch in <b>this repo</b> and opens a PR — your default branch is never touched.</p>
                )}
                {pr.status === 'working' && <p className="mono" aria-live="polite">This usually takes 5–15 seconds. Nothing is pushed until the diff is ready.</p>}
              </div>
            )}
            {pr.status === 'done' && pr.result && (
              <div aria-live="polite">
                {pr.result.pr ? (
                  <p>
                    <b>{pr.result.status === 'unchanged' ? 'A PR with these changes is already open' : pr.result.status === 'updated' ? 'Existing PR updated' : 'Pull request opened'}:</b>{' '}
                    <a href={pr.result.pr.url} target="_blank" rel="noreferrer">{pr.result.pr.url}</a>
                  </p>
                ) : (
                  <p className="mono">{pr.result.status === 'no-changes' ? 'This repo already matches the generated config — nothing to change.' : pr.result.status}</p>
                )}
                {pr.result.written?.map((w) => <p key={w.path} className="mono">＋ {w.path} — {w.what}</p>)}
                {pr.result.skipped?.map((s) => <p key={s.what} className="mono">Skipped {s.what}: {s.reason}</p>)}
              </div>
            )}
            {pr.status === 'install' && pr.result && (
              <div aria-live="polite">
                <p>{pr.result.message}</p>
                {pr.result.installUrl && (
                  <p><a className="sg-btn" href={pr.result.installUrl} target="_blank" rel="noreferrer">Install the Aperture App on GitHub</a></p>
                )}
                <p><button className="sg-btn" onClick={openPr}>I installed it — try again</button></p>
              </div>
            )}
            {pr.status === 'error' && (
              <p className="mono" aria-live="polite">{pr.error} <button className="sg-btn" onClick={openPr}>Retry</button></p>
            )}
          </section>

          <section aria-labelledby="repo-targets">
            <div className="ins-h" id="repo-targets"><span>Where fixes go in this repo</span></div>
            <table>
              <thead><tr><th>artifact</th><th>path</th><th>status</th></tr></thead>
              <tbody>
                <TargetRow label="robots.txt" target={report.editTargets.robots} />
                <TargetRow label="llms.txt" target={report.editTargets.llmsTxt} />
                <TargetRow label="sitemap" target={report.editTargets.sitemap} />
                <tr>
                  <td className="mono">JSON-LD</td>
                  <td className="mono">{report.editTargets.headTemplate ?? '—'}</td>
                  <td>{report.editTargets.headTemplate ? 'head template' : 'no head template found'}</td>
                </tr>
              </tbody>
            </table>
          </section>
        </div>
      )}
    </div>
  )
}
