/**
 * CLI for the repo-scan collector: GEO findings from a codebase instead of a deployed URL.
 *
 *   npx tsx src/runRepoScan.ts https://github.com/owner/repo
 *   npx tsx src/runRepoScan.ts ../some/local/checkout
 *
 * Prints the same six check cards as the URL diagnostics (with provenance, since pattern evidence
 * is weaker than probe evidence) plus the edit-target map the PR harness needs for placement.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { resolveRepo, scanRepo } from './repoScan/scan.js';
import type { RepoScanReport } from './repoScan/types.js';

const STATUS_ICON: Record<string, string> = { ok: 'OK  ', warn: 'WARN', bad: 'BAD ', na: 'N/A ' };

function printReport(report: RepoScanReport): void {
  console.log(`\nGEO repo scan: ${report.source}\n${'='.repeat(60)}`);
  console.log(
    `Framework: ${report.framework.framework} (rendering: ${report.framework.rendering})${report.appRoot ? `  app root: ${report.appRoot}/` : ''} — ${report.framework.evidence.join('; ')}\n`,
  );

  for (const c of report.checks) {
    console.log(`  ${STATUS_ICON[c.status]} ${c.label.padEnd(18)} ${c.headline}  [${c.provenance}]`);
    console.log(`       ${c.sub}`);
  }

  const t = report.editTargets;
  const show = (label: string, target: { path: string; exists: boolean; generated: boolean }) =>
    console.log(
      `  ${label.padEnd(12)} ${target.path}${target.exists ? (target.generated ? '  (generated by code)' : '  (exists)') : '  (missing — recommended location)'}`,
    );

  console.log(`\nEdit targets (placement map for the PR harness):`);
  show('robots.txt', t.robots);
  show('llms.txt', t.llmsTxt);
  show('sitemap', t.sitemap);
  console.log(`  ${'head/JSON-LD'.padEnd(12)} ${t.headTemplate ?? '(no head template found — agent must locate one)'}`);
  console.log(`  ${'static dir'.padEnd(12)} ${t.staticDir || '(repo root)'}`);
  console.log();
}

function writeSnapshot(report: RepoScanReport): string {
  const dir = join(process.cwd(), 'snapshots');
  mkdirSync(dir, { recursive: true });
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const slug = report.source.replace(/^https:\/\/(www\.)?github\.com\//, '').replace(/[^\w.-]+/g, '_').slice(0, 80);
  const file = join(dir, `${stamp}_repo_${slug}.json`);
  writeFileSync(file, JSON.stringify(report, null, 2));
  return file;
}

async function main() {
  const input = process.argv[2];
  if (!input) {
    console.error('Usage: npx tsx src/runRepoScan.ts <github-url-or-local-path>');
    process.exitCode = 1;
    return;
  }

  const { path, cleanup } = resolveRepo(input);
  try {
    const report = scanRepo(path, input);
    printReport(report);
    console.log(`Snapshot written: ${writeSnapshot(report)}\n`);
  } finally {
    cleanup();
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exitCode = 1;
});
